(()=>{
const API=()=>String(window.MAESTRO_SUBMISSION_API||'').replace(/\/$/,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().trim();
function ensure(){let host=document.querySelector('.mw-ask-maestro');if(host)return host;host=document.createElement('section');host.className='mw-ask-maestro';host.innerHTML='<form id="mw-ask-form"><div class="mw-ask-box"><input id="mw-ask-input" type="search" autocomplete="off" placeholder="Ask Maestro — search news, jobs, services, people, places and more…" aria-label="Ask Maestro"><button type="submit">SEARCH</button></div></form><div id="mw-search-results" class="mw-search-results" hidden></div>';let anchor=document.querySelector('.mw-submit-cta');(anchor||document.querySelector('.mw-masthead')).insertAdjacentElement('afterend',host);return host}
function local(q){const seen=new Set(), community=[], harvested=[];document.querySelectorAll('.mw-cloud-card,.mw-story,.mw-news-row,.mw-news-hero,article.card,.dating-card,.email-card').forEach(n=>{if(n.closest('#mw-search-results'))return;let txt=norm(n.innerText);if(!txt.includes(q))return;let title=(n.querySelector('h1,h2,h3')?.textContent||'Maestro record').trim(), desc=(n.querySelector('p,.desc,.summary')?.textContent||txt).trim().slice(0,260), a=n.querySelector('a[href]'), href=a?.href||location.href, key=title+'|'+href;if(seen.has(key))return;seen.add(key);let r={title,description:desc,url:href};(n.classList.contains('mw-cloud-card')?community:harvested).push(r)});return {community:community.slice(0,30),harvested:harvested.slice(0,40)}}
function cards(label,a,kind){if(!a.length)return '';return `<section class="mw-search-group"><h2>${esc(label)} <span>${a.length}</span></h2>${a.map(x=>`<article class="mw-search-result ${kind}"><div class="mw-search-source">${kind==='community'?'<img src="logo.png" alt=""> MAESTRO COMMUNITY':kind==='harvested'?'MAESTRO DATABASE':'WEB RESULT'}</div><h3><a target="_blank" rel="noopener" href="${esc(x.url||'#')}">${esc(x.title||'Result')}</a></h3><p>${esc(x.description||'')}</p></article>`).join('')}</section>`}
async function run(q){q=norm(q);if(!q)return;let out=document.querySelector('#mw-search-results');out.hidden=false;out.innerHTML='<div class="mw-searching">Searching Maestro…</div>';let l=local(q);out.innerHTML=cards('MAESTRO COMMUNITY',l.community,'community')+cards('MAESTRO DATABASE',l.harvested,'harvested')+'<div class="mw-web-wait">Searching the web…</div>';try{let r=await fetch(API()+'/api/search?q='+encodeURIComponent(q),{cache:'no-store'}),j=r.ok?await r.json():{};out.querySelector('.mw-web-wait')?.remove();out.insertAdjacentHTML('beforeend',cards('WEB RESULTS',j.results||[],'web')||'<p class="mw-search-empty">No additional web results are available.</p>')}catch{out.querySelector('.mw-web-wait')?.remove();out.insertAdjacentHTML('beforeend','<p class="mw-search-empty">Web search is temporarily unavailable.</p>')}out.scrollIntoView({behavior:'smooth',block:'start'})}
document.addEventListener('DOMContentLoaded',()=>{ensure();let f=document.querySelector('#mw-ask-form'),i=document.querySelector('#mw-ask-input');f.addEventListener('submit',e=>{e.preventDefault();run(i.value)});});
})();
