(()=>{
const API=()=>String(window.MAESTRO_SUBMISSION_API||'').replace(/\/$/,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().replace(/\s+/g,' ').trim();
const CARD_SEL='.mw-cloud-card,.mw-story,.mw-news-row,.mw-news-hero,article.card,.dating-card,.email-card,.mw-listing-row';
function ensure(){let host=document.querySelector('.mw-ask-maestro');if(!host){host=document.createElement('section');host.className='mw-ask-maestro';host.innerHTML='<form id="mw-ask-form"><div class="mw-ask-box"><input id="mw-ask-input" type="search" autocomplete="off" placeholder="Ask Maestro — search news, jobs, services, people, places and more…" aria-label="Ask Maestro"><button type="submit">SEARCH</button></div></form>';let anchor=document.querySelector('.mw-brandbar');if(anchor)anchor.insertAdjacentElement('afterend',host);else document.body.insertBefore(host,document.body.firstChild)}let feed=document.querySelector('#mw-search-feed');if(!feed){feed=document.createElement('main');feed.id='mw-search-feed';feed.className='mw-search-feed';feed.hidden=true;let tag=document.querySelector('.mw-v20-tagline');(tag||host).insertAdjacentElement('afterend',feed)}return{host,feed}}
function local(q){const seen=new Set(),community=[],harvested=[];document.querySelectorAll(CARD_SEL).forEach(n=>{if(n.closest('#mw-search-feed'))return;let txt=norm(n.innerText);if(!txt.includes(q))return;let title=(n.querySelector('h1,h2,h3')?.textContent||'Maestro record').trim(),desc=(n.querySelector('p,.desc,.summary')?.textContent||n.innerText||'').trim().slice(0,700),a=n.querySelector('a[href]'),href=a?.href||location.href,key=norm(title)+'|'+href;if(seen.has(key))return;seen.add(key);let r={title,description:desc,url:href};(n.classList.contains('mw-cloud-card')||/community/i.test(n.innerText)?community:harvested).push(r)});return{community,harvested}}
function setSearchMode(on){document.body.classList.toggle('mw-search-active',!!on);let feed=document.querySelector('#mw-search-feed');if(feed)feed.hidden=!on}
function row(x,kind){let label=kind==='community'?'MAESTRO WORLD VIEW · COMMUNITY':kind==='harvested'?'MAESTRO WORLD VIEW · DATABASE':'WEB SEARCH';let icon=kind==='web'?'':'<img class="mw-search-icon" src="logo.png" alt="">';return `<article class="mw-search-feed-row mw-news-row ${kind}"><div class="mw-search-feed-copy"><div class="mw-search-source">${icon}${label}</div><h3><a target="_blank" rel="noopener" href="${esc(x.url||'#')}">${esc(x.title||'Result')}</a></h3><p>${esc(x.description||'')}</p><a class="mw-search-open" target="_blank" rel="noopener" href="${esc(x.url||'#')}">READ MORE</a></div></article>`}
function group(label,a,kind){if(!a.length)return'';return `<section class="mw-search-feed-group"><div class="mw-search-feed-heading">${esc(label)} <span>${a.length}</span></div>${a.map(x=>row(x,kind)).join('')}</section>`}
function clearSearch(){let feed=document.querySelector('#mw-search-feed'),i=document.querySelector('#mw-ask-input');setSearchMode(false);if(feed)feed.innerHTML='';if(i)i.value=''}
async function run(raw){let q=norm(raw);if(!q){clearSearch();return}let {feed}=ensure(),l=local(q);setSearchMode(true);feed.innerHTML='<div class="mw-search-feed-toolbar"><strong>SEARCH RESULTS FOR “'+esc(raw.trim())+'”</strong><button type="button" id="mw-clear-search">CLEAR SEARCH</button></div>'+group('MAESTRO COMMUNITY',l.community,'community')+group('MAESTRO DATABASE',l.harvested,'harvested')+'<div class="mw-web-wait">Searching the web…</div>';feed.querySelector('#mw-clear-search')?.addEventListener('click',clearSearch);try{let r=await fetch(API()+'/api/search?q='+encodeURIComponent(raw.trim()),{cache:'no-store'}),j=r.ok?await r.json():{};feed.querySelector('.mw-web-wait')?.remove();let web=(j.results||[]);let html=group('WEB RESULTS',web,'web');if(html)feed.insertAdjacentHTML('beforeend',html);if(!l.community.length&&!l.harvested.length&&!web.length)feed.insertAdjacentHTML('beforeend','<p class="mw-search-empty">No results found for “'+esc(raw.trim())+'”.</p>')}catch{feed.querySelector('.mw-web-wait')?.remove();if(!l.community.length&&!l.harvested.length)feed.insertAdjacentHTML('beforeend','<p class="mw-search-empty">No Maestro matches found. Web search is temporarily unavailable.</p>')}feed.scrollIntoView({behavior:'smooth',block:'start'})}
document.addEventListener('DOMContentLoaded',()=>{ensure();let f=document.querySelector('#mw-ask-form'),i=document.querySelector('#mw-ask-input');f?.addEventListener('submit',e=>{e.preventDefault();run(i.value)});i?.addEventListener('search',()=>{if(!i.value.trim())clearSearch()})});
})();
