(()=>{
const api=()=>String(window.MAESTRO_SUBMISSION_API||"").replace(/\/$/,"");
const e=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const abs=u=>{u=String(u||"");return !u?"":/^https?:\/\//i.test(u)?u:api()+u};
async function g(p){try{let r=await fetch(api()+p,{cache:"no-store"});return r.ok?await r.json():[]}catch{return[]}}
function notify(){document.dispatchEvent(new CustomEvent("maestro:cloud-updated"));}
function stamp(v){try{return new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"numeric"}).format(new Date(v))}catch{return""}}
function communityMeta(x){return `<div class="src mw-community-meta"><img class="mw-source-icon mw-community-icon" src="logo.png" alt="Maestro World View"><span class="mw-community-label">MAESTRO WORLD VIEW · COMMUNITY SUBMISSION</span>${x.city||x.country?` · ${e([x.city,x.country].filter(Boolean).join(" · "))}`:""}${x.created_at?` · ${e(stamp(x.created_at))}`:""}</div>`}
function listingCard(x,section,mode){
 const img=abs(x.image_url)||"logo1.png";
 const link=`community_article.html?id=${encodeURIComponent(x.id||"")}&section=${encodeURIComponent(section||x.section||"")}`;
 const raw=String(x.description||"");
 const desc=e(raw.length>320?raw.slice(0,317).trimEnd()+"…":raw);
 const extra=[x.organization,x.price].filter(Boolean).map(e).join(" · ");
 if(mode==="market") return `<article class="card mw-cloud-card" data-cloud-id="${e(x.id)}" data-country="${e(x.country)}" data-city="${e(x.city)}" data-type="${e(section)}"><img class="mw-feed-image" src="${e(img)}" alt="" loading="lazy" onerror="this.onerror=null;this.src='logo1.png'"><div>${communityMeta(x)}<h2>${e(x.title)}</h2>${extra?`<div class="facts">${extra}</div>`:""}<p class="desc">${desc}</p>${x.contact_email?`<div class="contact">${e(x.contact_email)}</div>`:""}${link?`<a class="mw-source-button" target="_blank" rel="noopener" href="${e(link)}">READ MORE</a>`:""}</div></article>`;
 if(mode==="listing") return `<article class="mw-listing-row mw-story mw-cloud-card" data-cloud-id="${e(x.id)}" data-country="${e(x.country)}" data-city="${e(x.city)}" data-type="${e(section)}"><img class="mw-feed-image mw-listing-thumb" src="${e(img)}" alt="" loading="lazy" onerror="this.onerror=null;this.src='logo1.png'"><div class="mw-listing-copy">${communityMeta(x)}<h3>${e(x.title)}</h3>${extra?`<div class="mw-cloud-facts">${extra}</div>`:""}<p>${desc}</p>${link?`<a class="mw-source-button" target="_blank" rel="noopener" href="${e(link)}">READ MORE</a>`:""}</div></article>`;
 return `<article class="mw-news-row mw-story mw-cloud-card" data-cloud-id="${e(x.id)}" data-country="${e(x.country)}" data-city="${e(x.city)}" data-type="${e(section)}"><img class="mw-feed-image mw-news-thumb" src="${e(img)}" alt="" loading="lazy" onerror="this.onerror=null;this.src='logo1.png'"><div class="mw-news-row-copy">${communityMeta(x)}<h3>${e(x.title)}</h3>${extra?`<div class="mw-cloud-facts">${extra}</div>`:""}<p>${desc}</p>${link?`<a class="mw-source-button" target="_blank" rel="noopener" href="${e(link)}">READ MORE</a>`:""}</div></article>`;
}
function targetFor(section){
 const scoped=document.querySelector(`.mw-editorial-section[data-mw-section="${CSS.escape(section)}"]`);if(scoped){let vm=scoped.querySelector(".mw-view-more-wrap");return{host:scoped,before:vm||null,mode:scoped.querySelector(".mw-listing-row")?"listing":"news"}}
 const market=["job","service","real_estate","vehicle","art"].includes(section);
 if(market){let first=document.querySelector("article.card");if(first)return {host:first.parentElement,before:first,mode:"market"};let h=document.querySelector("header h1")?.parentElement||document.querySelector("main")||document.body;return{host:h,before:null,mode:"market"}}
 let latest=document.querySelector(".mw-latest");if(latest){let head=latest.querySelector(".mw-editorial-head");return{host:latest,before:head?head.nextSibling:latest.firstChild,mode:"news"}}
 let main=document.querySelector(".mw-section-wrap,.wrap,main")||document.body;return{host:main,before:null,mode:"news"};
}
function replaceCloud(section,a){document.querySelectorAll(`.mw-cloud-card[data-type="${CSS.escape(section)}"]`).forEach(n=>n.remove());let t=targetFor(section);let box=document.createElement("div");box.innerHTML=a.map(x=>listingCard(x,section,t.mode)).join("");let nodes=[...box.children];if(t.before)nodes.reverse().forEach(n=>t.host.insertBefore(n,t.before));else nodes.forEach(n=>t.host.appendChild(n));notify();}
window.loadSubmittedListings=async function(section){let a=await g("/api/listings/"+section);replaceCloud(section,a);window.__mwCloudTimers=window.__mwCloudTimers||{};if(!window.__mwCloudTimers[section])window.__mwCloudTimers[section]=setInterval(()=>window.loadSubmittedListings(section),30000)};
window.loadSubmittedResumes=async()=>{let h=document.querySelector("#submitted-resumes");if(!h)return;let a=await g("/api/resumes");h.innerHTML=a.map(x=>`<article class="card mw-story mw-cloud-card" data-country="${e(x.country)}" data-city="${e(x.city)}" data-type="resume" data-role="${e([x.job_title,x.profession,x.organization].filter(Boolean).join(" "))}" data-skills="${e(x.resume_text||"")}">${x.profile_image_url?`<img class="mw-feed-image" src="${e(abs(x.profile_image_url))}" alt="">`:""}<div><div class="src"><span class="mw-community-label">MAESTRO WORLD VIEW · COMMUNITY SUBMISSION</span></div><h2>${e(x.first_name+" "+(x.last_name||""))}</h2><h3>${e(x.headline||x.current_role||"Professional profile")}</h3><p>${e(x.summary||"")}</p></div></article>`).join("");notify()};
window.loadSubmittedDating=async()=>{let h=document.querySelector("#submitted-dating");if(!h)return;let a=await g("/api/dating");h.innerHTML=a.map(x=>`<article class="dating-card mw-story mw-cloud-card" data-country="${e(x.country)}" data-city="${e(x.city)}" data-type="dating" data-age="${e(x.age||"")}" data-gender="${e((String(x.bio||"").match(/Gender:\s*([^\n]+)/i)||[])[1]||"")}" data-goal="${e((String(x.bio||"").match(/Relationship goal:\s*([^\n]+)/i)||[])[1]||"")}"><div class="dating-copy"><div class="src"><span class="mw-community-label">MAESTRO WORLD VIEW · COMMUNITY SUBMISSION</span></div><h2>${e(x.first_name+" "+(x.last_name||""))}, ${e(x.age)}</h2><h3>${e(x.headline||"Dating profile")}</h3><p>${e(x.bio||"")}</p></div></article>`).join("");notify()};
})();
